apiVersion: v1
kind: Service
metadata:
  name: restaurant-landing
spec:
  selector:
    app: restaurant-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 31795  # Add this line
  type: NodePort         # Change this line

