apiVersion: apps/v1
kind: Deployment
metadata:
  name: restaurant-landing
spec:
  replicas: 1
  selector:
    matchLabels:
      app: restaurant-landing
  template:
    metadata:
      labels:
        app: restaurant-landing
    spec:
      containers:
        - name: web
          image: tyvenchr/restaurant-landing-page:1.0.10 # {"$imagepolicy": "flux-system:restaurant-latest"}
          imagePullPolicy: Always
          ports:
            - containerPort: 3000
