apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - deployment.yaml
  - service.yaml
  - image-automation/
images:
  - name: tyvenchr/restaurant-landing-page:1.0.5 # {"$imagepolicy": "flux-system:restaurant-latest"}
