apiVersion: v1
kind: Service
metadata:
  name: restaurant-landing
  namespace: default
spec:
  selector:
    app: restaurant-landing
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort

