apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: restaurant
  namespace: flux-system
spec:
  interval: 1m
  path: ../restaurant-app
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system

