apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImagePolicy
metadata:
  name: restaurant-latest
  namespace: flux-system
spec:
  imageRepositoryRef:
    name: restaurant
#  policy:
#    latest: {}
#  policy:
#    tag:
#      pattern: latest
  policy:
    semver:
      range: 1.0.x
#  policy:
#    alphabetical:
#      order: desc
