apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageUpdateAutomation
metadata:
  name: restaurant-update
  namespace: flux-system
spec:
  interval: 1m
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  git:
    checkout:
      ref:
        branch: main
    commit:
      author:
        name: FluxCD
        email: fluxcd@example.com
      messageTemplate: "Update image to {{range .Updated.Images}}{{.}}{{end}}"
    push:
      branch: main
